services:
  # Redis - Data persistence layer
  redis:
    image: redis:7-alpine
    container_name: claude-redis
    command: redis-server --requirepass ${REDIS_PASSWORD}
    ports:
      - "${REDIS_PORT:-6379}:6379"
    volumes:
      - ./redis/data:/data
      - ./logs/redis:/var/log/redis
    environment:
      - TZ=${TZ:-Asia/Seoul}
    networks:
      - claude-network
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "${REDIS_PASSWORD}", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  # Kong - API Gateway with AWS masking
  kong:
    build:
      context: ./kong
      dockerfile: Dockerfile
    container_name: claude-kong
    depends_on:
      redis:
        condition: service_healthy
    environment:
      - KONG_DATABASE=off
      - KONG_DECLARATIVE_CONFIG=/usr/local/kong/declarative/kong-${KONG_CONFIG_MODE:-traditional}.yml
      - KONG_PROXY_ACCESS_LOG=/usr/local/kong/logs/access.log
      - KONG_ADMIN_ACCESS_LOG=/usr/local/kong/logs/admin-access.log
      - KONG_PROXY_ERROR_LOG=/usr/local/kong/logs/error.log
      - KONG_ADMIN_ERROR_LOG=/usr/local/kong/logs/admin-error.log
      - KONG_PROXY_LISTEN=0.0.0.0:8010
      - KONG_ADMIN_LISTEN=0.0.0.0:8001
      - KONG_LOG_LEVEL=${KONG_LOG_LEVEL:-info}
      - KONG_MEM_CACHE_SIZE=${KONG_MEM_CACHE_SIZE:-2048m}
      - KONG_PLUGINS=bundled,aws-masker
      - KONG_LUA_PACKAGE_PATH=/usr/local/kong/plugins/?.lua;/usr/local/kong/plugins/?/init.lua;;
      
      # API Keys
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      
      # Traditional Redis configuration (default)
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      
      # ElastiCache configuration (for managed mode)
      - ELASTICACHE_HOST=${ELASTICACHE_HOST:-}
      - ELASTICACHE_PORT=${ELASTICACHE_PORT:-6379}
      - ELASTICACHE_AUTH_TOKEN=${ELASTICACHE_AUTH_TOKEN:-}
      - ELASTICACHE_USER=${ELASTICACHE_USER:-}
      - ELASTICACHE_CLUSTER_MODE=${ELASTICACHE_CLUSTER_MODE:-false}
      - ELASTICACHE_CLUSTER_ENDPOINT=${ELASTICACHE_CLUSTER_ENDPOINT:-}
      
      # Common configuration
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      - TZ=${TZ:-Asia/Seoul}
    volumes:
      # Original config file (backward compatibility)
      - ./kong/kong.yml:/usr/local/kong/declarative/kong.yml:ro
      # New environment-specific config files
      - ./kong/kong-traditional.yml:/usr/local/kong/declarative/kong-traditional.yml:ro
      - ./kong/kong-managed.yml:/usr/local/kong/declarative/kong-managed.yml:ro
      # Plugin files
      - ./kong/plugins:/usr/local/kong/plugins:ro
      # Log directory
      - ./logs/kong:/usr/local/kong/logs
    ports:
      - "${KONG_ADMIN_PORT:-8001}:8001"
      - "${KONG_PROXY_PORT:-8010}:8010"
    networks:
      - claude-network
    healthcheck:
      test: ["CMD", "kong", "health"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: ${KONG_MEMORY_LIMIT:-4G}
        reservations:
          cpus: '1.0'
          memory: 2G

  # Nginx - Enterprise proxy layer
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: claude-nginx
    depends_on:
      kong:
        condition: service_healthy
    ports:
      - "${NGINX_PROXY_PORT:-8082}:8082"
    volumes:
      - ./logs/nginx:/var/log/nginx
    environment:
      - NGINX_WORKER_PROCESSES=${NGINX_WORKER_PROCESSES:-auto}
      - NGINX_WORKER_CONNECTIONS=${NGINX_WORKER_CONNECTIONS:-1024}
      - TZ=${TZ:-Asia/Seoul}
    networks:
      - claude-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8082/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped

  # Claude Code SDK - Interactive CLI
  claude-code-sdk:
    build:
      context: ./claude-code-sdk
      dockerfile: Dockerfile
    container_name: claude-code-sdk
    depends_on:
      nginx:
        condition: service_healthy
    environment:
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      - HTTP_PROXY=http://nginx:8082
      - ANTHROPIC_BASE_URL=http://nginx:8082/v1
      - NO_PROXY=localhost,127.0.0.1
      - TZ=${TZ:-Asia/Seoul}
    volumes:
      - ./claude-code-sdk/scripts:/home/claude/scripts:ro
      - ./logs/claude-code-sdk:/home/claude/logs
      - ./tests:/home/claude/tests:ro
      - ./logs:/logs:ro
    networks:
      - claude-network
    stdin_open: true
    tty: true
    restart: unless-stopped

networks:
  claude-network:
    name: ${NETWORK_NAME:-claude-enterprise}
    driver: bridge
    ipam:
      config:
        - subnet: 172.29.0.0/16

volumes:
  redis-data:
  kong-logs:
  nginx-logs: