_format_version: "3.0"
_transform: true

# Kong AWS Masking MVP - Declarative Configuration
# This configuration sets up Kong Gateway in DB-less mode

services:
  - name: backend-api
    url: http://backend:3000
    protocol: http
    host: backend
    port: 3000
    path: /
    retries: 3
    connect_timeout: 5000
    write_timeout: 60000
    read_timeout: 60000
    tags:
      - backend
      - api
    
    routes:
      - name: analyze-route
        paths:
          - /analyze
        methods:
          - POST
        strip_path: false
        preserve_host: false
        tags:
          - aws-analysis
        
      - name: health-route
        paths:
          - /health
        methods:
          - GET
        strip_path: false
        tags:
          - health-check
          
      - name: aws-resource-route
        paths:
          - /aws
        methods:
          - GET
          - POST
        strip_path: false
        tags:
          - aws-resources

    plugins:
      - name: correlation-id
        config:
          header_name: X-Request-ID
          generator: uuid
          echo_downstream: true
          
      - name: request-transformer
        config:
          add:
            headers:
              - X-Kong-Proxy:true
              - X-Service-Name:backend-api
              
      - name: response-transformer
        config:
          add:
            headers:
              - X-Kong-Response:true
              - X-Response-Time:$(latency)

# Global plugins
plugins:
  - name: prometheus
    config:
      status_code_metrics: true
      latency_metrics: true
      bandwidth_metrics: true
      upstream_health_metrics: true
      
  - name: cors
    config:
      origins:
        - "*"
      methods:
        - GET
        - POST
        - PUT
        - DELETE
        - OPTIONS
      headers:
        - Accept
        - Accept-Version
        - Content-Length
        - Content-MD5
        - Content-Type
        - Date
        - X-Auth-Token
        - X-Request-ID
        - Authorization
      exposed_headers:
        - X-Auth-Token
        - X-Request-ID
      credentials: true
      max_age: 3600
      
  - name: rate-limiting
    config:
      minute: 60
      hour: 1000
      policy: local
      fault_tolerant: true
      hide_client_headers: false
      
  - name: request-size-limiting
    config:
      allowed_payload_size: 10
      size_unit: megabytes
      require_content_length: false

# Custom plugin configuration placeholder
# The aws-masker plugin will be configured here once implemented
# plugins:
#   - name: aws-masker
#     config:
#       mask_ec2_instances: true
#       mask_s3_buckets: true
#       mask_rds_instances: true
#       mask_private_ips: true
#       preserve_structure: true

# Upstreams configuration (for load balancing in future)
# upstreams:
#   - name: backend-upstream
#     targets:
#       - target: backend:3000
#         weight: 100
#     healthchecks:
#       active:
#         healthy:
#           interval: 5
#           successes: 1
#         unhealthy:
#           interval: 5
#           tcp_failures: 1
#           timeouts: 1
#           http_failures: 1