_format_version: "3.0"
_transform: true

# Kong AWS Masking MVP - Test Configuration
# Minimal configuration for testing and CI/CD environments

services:
  - name: backend-api-test
    url: http://backend:3001
    protocol: http
    host: backend
    port: 3001
    path: /
    retries: 1
    connect_timeout: 1000
    write_timeout: 5000
    read_timeout: 5000
    tags:
      - backend
      - test
    
    routes:
      - name: analyze-route-test
        paths:
          - /analyze
        methods:
          - POST
        strip_path: false
        preserve_host: false
        tags:
          - aws-analysis
          - test
        
      - name: health-route-test
        paths:
          - /health
        methods:
          - GET
        strip_path: false
        tags:
          - health-check
          - test
          
      # Mock route REMOVED - ZERO MOCK MODE policy
      # ALL routes must use real backend services

    plugins:
      - name: correlation-id
        config:
          header_name: X-Test-Request-ID
          generator: uuid
          echo_downstream: true
          
      - name: request-transformer
        config:
          add:
            headers:
              - X-Kong-Proxy:true
              - X-Service-Name:backend-api-test
              - X-Production-Ready:true

# Test-specific global plugins
plugins:
  - name: cors
    config:
      origins:
        - "*"
      methods:
        - GET
        - POST
        - PUT
        - DELETE
        - OPTIONS
        - HEAD
      headers:
        - "*"
      exposed_headers:
        - "*"
      credentials: true
      max_age: 86400
      
  - name: rate-limiting
    config:
      minute: 1000
      hour: 10000
      policy: local
      fault_tolerant: true
      hide_client_headers: true
      
  - name: request-size-limiting
    config:
      allowed_payload_size: 1
      size_unit: megabytes
      require_content_length: false