_format_version: "3.0"
_transform: true

# Kong AWS Masking MVP - Template Configuration
# Environment-specific values will be substituted during deployment

services:
  - name: backend-api
    url: ${BACKEND_SERVICE_URL:-http://backend:3000}
    protocol: http
    host: ${BACKEND_HOST:-backend}
    port: ${BACKEND_PORT:-3000}
    path: /
    retries: ${SERVICE_RETRIES:-3}
    connect_timeout: ${CONNECT_TIMEOUT:-5000}
    write_timeout: ${WRITE_TIMEOUT:-60000}
    read_timeout: ${READ_TIMEOUT:-60000}
    tags:
      - backend
      - api
      - ${ENVIRONMENT:-development}
    
    routes:
      - name: analyze-route
        paths:
          - /analyze
        methods:
          - POST
        strip_path: false
        preserve_host: false
        tags:
          - aws-analysis
          - ${ENVIRONMENT:-development}
        
      - name: health-route
        paths:
          - /health
        methods:
          - GET
        strip_path: false
        tags:
          - health-check
          - ${ENVIRONMENT:-development}
          
      - name: aws-resource-route
        paths:
          - /aws
        methods:
          - GET
          - POST
        strip_path: false
        tags:
          - aws-resources
          - ${ENVIRONMENT:-development}

    plugins:
      # AWS Masking Plugin (will be loaded when available)
      # - name: aws-masker
      #   config:
      #     mask_ec2_instances: ${MASK_EC2:-true}
      #     mask_s3_buckets: ${MASK_S3:-true}
      #     mask_rds_instances: ${MASK_RDS:-true}
      #     mask_private_ips: ${MASK_PRIVATE_IPS:-true}
      #     preserve_structure: ${PRESERVE_STRUCTURE:-true}
      #     log_masked_requests: ${LOG_MASKED_REQUESTS:-false}
      
      - name: correlation-id
        config:
          header_name: X-Request-ID
          generator: uuid
          echo_downstream: true
          
      - name: request-transformer
        config:
          add:
            headers:
              - X-Kong-Proxy:true
              - X-Service-Name:backend-api
              - X-Environment:${ENVIRONMENT:-development}
              
      - name: response-transformer
        config:
          add:
            headers:
              - X-Kong-Response:true
              - X-Response-Time:$(latency)
              - X-Environment:${ENVIRONMENT:-development}

# Global plugins with environment-specific configuration
plugins:
  - name: prometheus
    config:
      status_code_metrics: ${ENABLE_STATUS_METRICS:-true}
      latency_metrics: ${ENABLE_LATENCY_METRICS:-true}
      bandwidth_metrics: ${ENABLE_BANDWIDTH_METRICS:-true}
      upstream_health_metrics: ${ENABLE_UPSTREAM_HEALTH_METRICS:-true}
      
  - name: cors
    config:
      origins: ${CORS_ORIGINS:-["*"]}
      methods:
        - GET
        - POST
        - PUT
        - DELETE
        - OPTIONS
      headers:
        - Accept
        - Accept-Version
        - Content-Length
        - Content-MD5
        - Content-Type
        - Date
        - X-Auth-Token
        - X-Request-ID
        - Authorization
      exposed_headers:
        - X-Auth-Token
        - X-Request-ID
      credentials: ${CORS_CREDENTIALS:-true}
      max_age: ${CORS_MAX_AGE:-3600}
      
  - name: rate-limiting
    config:
      minute: ${RATE_LIMIT_MINUTE:-60}
      hour: ${RATE_LIMIT_HOUR:-1000}
      policy: ${RATE_LIMIT_POLICY:-local}
      fault_tolerant: true
      hide_client_headers: ${HIDE_RATE_LIMIT_HEADERS:-false}
      
  - name: request-size-limiting
    config:
      allowed_payload_size: ${MAX_PAYLOAD_SIZE:-10}
      size_unit: megabytes
      require_content_length: false

# Environment-specific upstreams
upstreams:
  - name: backend-upstream
    algorithm: ${LOAD_BALANCE_ALGORITHM:-round-robin}
    targets:
      - target: ${BACKEND_HOST:-backend}:${BACKEND_PORT:-3000}
        weight: 100
    healthchecks:
      active:
        type: http
        http_path: /health
        healthy:
          interval: ${HEALTH_CHECK_INTERVAL:-5}
          successes: ${HEALTH_CHECK_SUCCESSES:-1}
        unhealthy:
          interval: ${HEALTH_CHECK_INTERVAL:-5}
          tcp_failures: ${HEALTH_CHECK_TCP_FAILURES:-1}
          timeouts: ${HEALTH_CHECK_TIMEOUTS:-1}
          http_failures: ${HEALTH_CHECK_HTTP_FAILURES:-1}