version: '3.8'

services:
  # Nginx 프록시 서버
  nginx-proxy:
    image: nginx:alpine
    container_name: sdk-test-proxy
    ports:
      - "8888:80"
    volumes:
      - ./nginx-proxy/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./results/logs:/var/log/nginx
    networks:
      - sdk-test-net
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:80/health"]
      interval: 10s
      timeout: 5s
      retries: 3
    
  # Kong 프록시 (선택사항)
  kong-minimal:
    image: kong:3.9-ubuntu
    container_name: sdk-test-kong
    environment:
      - KONG_DATABASE=off
      - KONG_DECLARATIVE_CONFIG=/kong.yml
      - KONG_PROXY_ACCESS_LOG=/dev/stdout
      - KONG_PROXY_ERROR_LOG=/dev/stderr
      - KONG_ADMIN_ACCESS_LOG=/dev/stdout
      - KONG_ADMIN_ERROR_LOG=/dev/stderr
    ports:
      - "8000:8000"
      - "8001:8001"
    volumes:
      - ./kong-minimal/kong.yml:/kong.yml:ro
      - ./results/logs:/logs
    networks:
      - sdk-test-net
    healthcheck:
      test: ["CMD", "kong", "health"]
      interval: 10s
      timeout: 5s
      retries: 3
      
  # SDK 테스트 컨테이너
  sdk-tester:
    build: .
    container_name: sdk-tester
    environment:
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      - PROXY_URL=http://nginx-proxy:80
      - KONG_URL=http://kong-minimal:8000
      - NODE_ENV=test
    volumes:
      - ./src:/app/src:ro
      - ./results:/app/results
    depends_on:
      - nginx-proxy
      - kong-minimal
    networks:
      - sdk-test-net
    # 네트워크 격리 - api.anthropic.com 직접 접근 차단
    extra_hosts:
      - "api.anthropic.com:127.0.0.1"
    command: sh -c "sleep 5 && node src/test-sdk-proxy.js"

networks:
  sdk-test-net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.30.0.0/16
    driver_opts:
      com.docker.network.bridge.name: sdk-test-br