# Nginx Configuration for Kong Gateway Proxy
# High-performance proxy configuration with security and monitoring
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: kong-aws-masking
  labels:
    app: nginx-proxy
    component: configuration
    version: "enterprise-v2.0.0"
data:
  # Main Nginx configuration
  nginx.conf: |
    # Nginx Configuration for Kong AWS Masking Enterprise
    # High-performance proxy with security features
    
    user nginx;
    worker_processes auto;
    error_log /var/log/nginx/error.log warn;
    pid /var/run/nginx.pid;
    
    # Load modules
    load_module modules/ngx_http_realip_module.so;
    
    events {
        worker_connections 1024;
        use epoll;
        multi_accept on;
    }
    
    http {
        # Basic settings
        include /etc/nginx/mime.types;
        default_type application/octet-stream;
        
        # Logging format
        log_format main '$remote_addr - $remote_user [$time_local] "$request" '
                       '$status $body_bytes_sent "$http_referer" '
                       '"$http_user_agent" "$http_x_forwarded_for" '
                       'rt=$request_time uct="$upstream_connect_time" '
                       'uht="$upstream_header_time" urt="$upstream_response_time"';
        
        # Enhanced logging for Claude API requests
        log_format claude_api '$remote_addr - $remote_user [$time_local] "$request" '
                             '$status $body_bytes_sent "$http_referer" '
                             '"$http_user_agent" "$http_x_forwarded_for" '
                             'rt=$request_time uct="$upstream_connect_time" '
                             'uht="$upstream_header_time" urt="$upstream_response_time" '
                             'kong_request_id="$upstream_http_x_kong_request_id" '
                             'aws_masker_status="$upstream_http_x_kong_aws_masker"';
        
        access_log /var/log/nginx/access.log claude_api;
        
        # Performance settings
        sendfile on;
        tcp_nopush on;
        tcp_nodelay on;
        keepalive_timeout 65;
        types_hash_max_size 2048;
        client_max_body_size 10M;
        
        # Buffer settings
        client_body_buffer_size 16K;
        client_header_buffer_size 1k;
        large_client_header_buffers 4 8k;
        client_body_timeout 12;
        client_header_timeout 12;
        send_timeout 10;
        
        # Gzip compression
        gzip on;
        gzip_vary on;
        gzip_proxied any;
        gzip_comp_level 6;
        gzip_types
            text/plain
            text/css
            text/xml
            text/javascript
            application/json
            application/javascript
            application/xml+rss
            application/atom+xml
            image/svg+xml;
        
        # Security headers
        add_header X-Frame-Options DENY always;
        add_header X-Content-Type-Options nosniff always;
        add_header X-XSS-Protection "1; mode=block" always;
        add_header Referrer-Policy "strict-origin-when-cross-origin" always;
        
        # Rate limiting zones
        limit_req_zone $binary_remote_addr zone=api_limit:10m rate=10r/s;
        limit_req_zone $binary_remote_addr zone=auth_limit:10m rate=5r/s;
        
        # Connection limiting
        limit_conn_zone $binary_remote_addr zone=conn_limit:10m;
        
        # Upstream configuration for Kong Gateway
        upstream kong_gateway {
            least_conn;
            server kong-gateway-service:8000 max_fails=3 fail_timeout=30s;
            keepalive 32;
        }
        
        # Health check upstream
        upstream kong_admin {
            server kong-admin-service:8001 max_fails=2 fail_timeout=10s;
            keepalive 8;
        }
        
        # Include additional configurations
        include /etc/nginx/conf.d/*.conf;
    }
  
  # Claude Proxy Configuration
  claude-proxy.conf: |
    # Kong Gateway Proxy Configuration for Claude API
    # Enterprise security and performance features
    
    server {
        listen 8082;
        server_name nginx-proxy nginx-proxy-service localhost;
        
        # Basic security settings
        server_tokens off;
        
        # Connection and rate limiting
        limit_conn conn_limit 50;
        limit_req zone=api_limit burst=20 nodelay;
        
        # Real IP configuration for EKS/AWS
        set_real_ip_from 10.0.0.0/16;
        set_real_ip_from 172.16.0.0/12;
        set_real_ip_from 192.168.0.0/16;
        real_ip_header X-Forwarded-For;
        real_ip_recursive on;
        
        # Health check endpoint
        location /health {
            access_log off;
            return 200 '{"status":"healthy","service":"nginx-proxy","timestamp":"$time_iso8601","version":"enterprise-v2.0.0"}';
            add_header Content-Type application/json;
            add_header X-Service-Health "OK";
        }
        
        # Nginx status for monitoring
        location /nginx_status {
            stub_status on;
            access_log off;
            allow 127.0.0.1;
            allow 10.0.0.0/16;    # EKS pod network
            allow 172.16.0.0/12;  # Docker network
            deny all;
        }
        
        # Claude API proxy (main endpoint)
        location /v1/ {
            # Rate limiting for API requests
            limit_req zone=api_limit burst=50 nodelay;
            
            # Proxy settings
            proxy_pass http://kong_gateway;
            proxy_http_version 1.1;
            proxy_set_header Connection "";
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_set_header X-Forwarded-Port $server_port;
            
            # Custom headers for Kong plugin
            proxy_set_header X-Nginx-Proxy "enterprise-v2.0.0";
            proxy_set_header X-Request-Start $msec;
            proxy_set_header X-Original-URI $request_uri;
            
            # Timeout settings
            proxy_connect_timeout 10s;
            proxy_send_timeout 30s;
            proxy_read_timeout 60s;
            
            # Buffer settings
            proxy_buffering on;
            proxy_buffer_size 4k;
            proxy_buffers 8 4k;
            proxy_busy_buffers_size 8k;
            
            # Error handling
            proxy_next_upstream error timeout invalid_header http_500 http_502 http_503;
            proxy_next_upstream_tries 2;
            proxy_next_upstream_timeout 10s;
            
            # Custom error pages
            error_page 502 503 504 /50x.html;
        }
        
        # Kong Admin API proxy (internal monitoring)
        location /kong-admin/ {
            # Restrict access to internal networks only
            allow 10.0.0.0/16;    # EKS pod network
            allow 172.16.0.0/12;  # Docker network  
            allow 127.0.0.1;      # Localhost
            deny all;
            
            # Remove /kong-admin prefix
            rewrite ^/kong-admin/(.*) /$1 break;
            
            proxy_pass http://kong_admin;
            proxy_http_version 1.1;
            proxy_set_header Connection "";
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            
            # Timeout settings for admin API
            proxy_connect_timeout 5s;
            proxy_send_timeout 10s;
            proxy_read_timeout 15s;
        }
        
        # Monitoring and metrics endpoint
        location /monitoring/ {
            # Internal access only
            allow 10.0.0.0/16;
            allow 172.16.0.0/12;
            allow 127.0.0.1;
            deny all;
            
            # Proxy to monitoring services
            proxy_pass http://monitoring-service:8080/;
            proxy_http_version 1.1;
            proxy_set_header Connection "";
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }
        
        # Error pages
        location = /50x.html {
            root /usr/share/nginx/html;
            internal;
        }
        
        # Security: Block access to hidden files
        location ~ /\. {
            deny all;
            access_log off;
            log_not_found off;
        }
        
        # Security: Block access to backup files
        location ~ ~$ {
            deny all;
            access_log off;
            log_not_found off;
        }
    }
    
    # Additional server for SSL termination (future enhancement)
    # server {
    #     listen 8443 ssl http2;
    #     server_name nginx-proxy nginx-proxy-service;
    #     
    #     ssl_certificate /etc/ssl/certs/nginx-proxy.crt;
    #     ssl_certificate_key /etc/ssl/private/nginx-proxy.key;
    #     ssl_protocols TLSv1.2 TLSv1.3;
    #     ssl_ciphers ECDHE-RSA-AES256-GCM-SHA512:DHE-RSA-AES256-GCM-SHA512:ECDHE-RSA-AES256-GCM-SHA384:DHE-RSA-AES256-GCM-SHA384;
    #     ssl_prefer_server_ciphers off;
    #     
    #     # Include the same location blocks as HTTP server
    # }