apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kong-aws-masking.fullname" . }}-secrets
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "kong-aws-masking.labels" . | nindent 4 }}
type: Opaque
data:
  # Claude API Key
  claude-api-key: {{ .Values.secrets.claude.apiKey | b64enc | quote }}
  
  # AWS Credentials
  aws-access-key-id: {{ .Values.secrets.aws.accessKeyId | b64enc | quote }}
  aws-secret-access-key: {{ .Values.secrets.aws.secretAccessKey | b64enc | quote }}
  aws-region: {{ .Values.secrets.aws.region | b64enc | quote }}
  
  # Redis Password
  redis-password: {{ .Values.secrets.redis.password | b64enc | quote }}
---
{{- if eq .Values.global.environment "localstack" }}
# LocalStack-specific configmap for AWS endpoints
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "kong-aws-masking.fullname" . }}-localstack-config
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "kong-aws-masking.labels" . | nindent 4 }}
data:
  LOCALSTACK_HOSTNAME: "localstack"
  AWS_ENDPOINT_URL: "http://localstack:4566"
  AWS_DEFAULT_REGION: "us-east-1"
  # Override AWS credentials for LocalStack
  AWS_ACCESS_KEY_ID: "test"
  AWS_SECRET_ACCESS_KEY: "test"
{{- end }}