_format_version: "3.0"
_transform: true

services:
  - name: claude-api-service
    url: https://api.anthropic.com/v1/messages
    protocol: https
    host: api.anthropic.com
    port: 443
    path: /v1/messages
    retries: 3
    connect_timeout: 5000
    write_timeout: 60000
    read_timeout: 60000
    tags:
      - claude
      - production

routes:
  - name: claude-proxy-route
    service: claude-api-service
    paths:
      - /claude-proxy/v1/messages
      - /v1/messages
    methods:
      - POST
    strip_path: false
    preserve_host: false
    regex_priority: 0
    tags:
      - claude
      - proxy

plugins:
  - name: aws-masker
    route: claude-proxy-route
    config:
      # Redis configuration
      use_redis: true
      redis_host: redis
      redis_port: 6379
      redis_password: "${REDIS_PASSWORD}"
      redis_database: 0
      redis_timeout: 2000
      redis_keepalive_timeout: 60000
      redis_keepalive_pool_size: 30
      
      # Masking features
      mask_ec2_instances: true
      mask_s3_buckets: true
      mask_rds_instances: true
      mask_elasticache_clusters: true
      mask_eks_clusters: true
      mask_lambda_functions: true
      mask_vpc_ids: true
      mask_subnet_ids: true
      mask_security_groups: true
      mask_private_ips: true
      mask_iam_roles: true
      mask_iam_users: true
      mask_kms_keys: true
      mask_sns_topics: true
      mask_sqs_queues: true
      mask_dynamodb_tables: true
      mask_efs_filesystems: true
      mask_elb_names: true
      mask_cloudfront_distributions: true
      mask_route53_zones: true
      
      # Advanced options
      preserve_structure: true
      log_masked_requests: true
      log_level: info
      mapping_ttl: 86400  # 24 hours
      max_body_size: 10485760  # 10MB
      enable_metrics: true
      enable_health_check: true
      
      # Event publishing
      publish_events: true
      event_channel: "aws-masking-events"
      
      # Performance tuning
      cache_size: 10000
      batch_size: 100
      worker_pool_size: 4
    tags:
      - security
      - masking

  - name: correlation-id
    config:
      header_name: X-Correlation-ID
      generator: uuid
      echo_downstream: true
    tags:
      - observability

  - name: request-transformer
    route: claude-proxy-route
    config:
      add:
        headers:
          - "anthropic-version:2023-06-01"
      remove:
        headers:
          - "X-Real-IP"
          - "X-Forwarded-For"
    tags:
      - security

  - name: response-transformer
    route: claude-proxy-route
    config:
      add:
        headers:
          - "X-Kong-Proxy:true"
          - "X-Masked-Response:true"
    tags:
      - metadata

upstreams:
  - name: claude-api-upstream
    algorithm: round-robin
    slots: 10000
    healthchecks:
      active:
        healthy:
          interval: 30
          successes: 2
        unhealthy:
          interval: 5
          http_failures: 5
          tcp_failures: 5
          timeouts: 5
      passive:
        healthy:
          successes: 2
        unhealthy:
          http_failures: 5
          tcp_failures: 5
          timeouts: 5
    tags:
      - claude
      - production