# Redis Deployment for ElastiCache Simulation
# Simple Redis deployment to test Kong Plugin ElastiCache integration
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-elasticache
  namespace: kong-aws-masking
  labels:
    app: redis-elasticache
    component: cache
    version: "7.0"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-elasticache
  template:
    metadata:
      labels:
        app: redis-elasticache
        component: cache
        version: "7.0"
    spec:
      containers:
      - name: redis
        image: redis:7.0-alpine
        ports:
        - containerPort: 6379
          name: redis
        command:
        - redis-server
        - --port
        - "6379"
        - --bind
        - "0.0.0.0"
        - --maxmemory
        - "256mb"
        - --maxmemory-policy
        - "allkeys-lru"
        - --tcp-keepalive
        - "60"
        - --timeout
        - "300"
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        livenessProbe:
          tcpSocket:
            port: redis
          initialDelaySeconds: 10
          periodSeconds: 10
        readinessProbe:
          exec:
            command:
            - redis-cli
            - ping
          initialDelaySeconds: 5
          periodSeconds: 5
---
# Redis Service for ElastiCache Simulation
apiVersion: v1
kind: Service
metadata:
  name: redis-elasticache-service
  namespace: kong-aws-masking
  labels:
    app: redis-elasticache
    component: cache
spec:
  type: ClusterIP
  ports:
  - port: 6379
    targetPort: redis
    protocol: TCP
    name: redis
  selector:
    app: redis-elasticache
---
# Redis Service with Custom Port (4510) for LocalStack Compatibility
apiVersion: v1
kind: Service
metadata:
  name: redis-localstack-service
  namespace: kong-aws-masking
  labels:
    app: redis-elasticache
    component: cache-localstack
spec:
  type: ClusterIP
  ports:
  - port: 4510
    targetPort: redis
    protocol: TCP
    name: redis-localstack
  selector:
    app: redis-elasticache